In [41]:
import requests ,json
import pandas as pd

In [33]:
API_key='xyz'
city_name= 'Ahmedabad'
url=f"http://api.openweathermap.org/geo/1.0/direct?q={city_name},&appid={API_key}"
response = requests.get(url)
# response.status_code
result= response.json()
result

[{'name': 'Ahmedabad',
  'local_names': {'ur': 'احمد آباد',
   'de': 'Ahmedabad',
   'pa': 'ਅਹਿਮਦਾਬਾਦ',
   'mr': 'अहमदाबाद',
   'te': 'అహ్మదాబాద్',
   'zh': '艾哈迈达巴德',
   'ascii': 'Ahmedabad',
   'ml': 'അഹമ്മദാബാദ്',
   'eo': 'Ahmadabado',
   'hi': 'अहमदाबाद',
   'ta': 'அகமதாபாத்',
   'or': 'ଅହମଦାବାଦ',
   'tt': 'Әхмәтабад',
   'pl': 'Ahmadabad',
   'he': 'אחמדאבאד',
   'cs': 'Ahmadábád',
   'bn': 'আহমেদাবাদ',
   'uk': 'Ахмедабад',
   'kn': 'ಅಹ್ಮದಾಬಾದ್',
   'ne': 'अहमदाबाद',
   'feature_name': 'Ahmedabad',
   'en': 'Ahmedabad',
   'gu': 'અમદાવાદ',
   'ru': 'Ахмадабад',
   'ar': 'أحمد آباد',
   'oc': 'Ahmadabad',
   'ja': 'アフマダーバード'},
  'lat': 23.0215374,
  'lon': 72.5800568,
  'country': 'IN',
  'state': 'Gujarat'}]

In [34]:
lat=result[0]['lat']
lon=result[0]['lon']

In [35]:
lat,lon

(23.0215374, 72.5800568)

In [36]:
url2=f"http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={API_key}"
response = requests.get(url2)
response.status_code
result2= response.json()
for i,j in result2['list'][0]['components'].items():
    print(i," : ",j)

co  :  108.92
no  :  0.19
no2  :  1.04
o3  :  72.43
so2  :  1.8
pm2_5  :  14.49
pm10  :  40.34
nh3  :  8.21

In [44]:
url3=f"http://api.openweathermap.org/data/2.5/air_pollution/forecast?lat={lat}&lon={lon}&appid={API_key}"
response = requests.get(url3)
response.status_code
result= response.json()
result

{'coord': {'lon': 72.5801, 'lat': 23.0215},
 'list': [{'main': {'aqi': 2},
   'components': {'co': 110.29,
    'no': 0.29,
    'no2': 1.45,
    'o3': 62.74,
    'so2': 2.13,
    'pm2_5': 14.02,
    'pm10': 42.6,
    'nh3': 9.3},
   'dt': 1780466400},
  {'main': {'aqi': 2},
   'components': {'co': 108.92,
    'no': 0.19,
    'no2': 1.04,
    'o3': 72.43,
    'so2': 1.8,
    'pm2_5': 14.49,
    'pm10': 40.34,
    'nh3': 8.21},
   'dt': 1780470000},
  {'main': {'aqi': 2},
   'components': {'co': 106.57,
    'no': 0.14,
    'no2': 0.85,
    'o3': 76.33,
    'so2': 1.43,
    'pm2_5': 13.31,
    'pm10': 35.19,
    'nh3': 7.05},
   'dt': 1780473600},
  {'main': {'aqi': 2},
   'components': {'co': 106.47,
    'no': 0.13,
    'no2': 0.84,
    'o3': 78.54,
    'so2': 1.3,
    'pm2_5': 12.8,
    'pm10': 33.05,
    'nh3': 6.74},
   'dt': 1780477200},
  {'main': {'aqi': 2},
   'components': {'co': 110.24,
    'no': 0.14,
    'no2': 1.01,
    'o3': 81.24,
    'so2': 1.27,
    'pm2_5': 12.69,
    'pm10': 32.31,
    'nh3': 7.21},
   'dt': 1780480800},
  {'main': {'aqi': 2},
   'components': {'co': 116.48,
    'no': 0.18,
    'no2': 1.47,
    'o3': 82.78,
    'so2': 1.33,
    'pm2_5': 12.61,
    'pm10': 31.87,
    'nh3': 8.18},
   'dt': 1780484400},
  {'main': {'aqi': 2},
   'components': {'co': 122.11,
    'no': 0.21,
    'no2': 2.21,
    'o3': 81.46,
    'so2': 1.43,
    'pm2_5': 12.15,
    'pm10': 31.04,
    'nh3': 8.87},
   'dt': 1780488000},
  {'main': {'aqi': 2},
   'components': {'co': 126.45,
    'no': 0.14,
    'no2': 3.08,
    'o3': 77.11,
    'so2': 1.58,
    'pm2_5': 11.47,
    'pm10': 30.79,
    'nh3': 9.49},
   'dt': 1780491600},
  {'main': {'aqi': 2},
   'components': {'co': 128.19,
    'no': 0.02,
    'no2': 3.62,
    'o3': 70.86,
    'so2': 1.8,
    'pm2_5': 10.9,
    'pm10': 31.73,
    'nh3': 9.91},
   'dt': 1780495200},
  {'main': {'aqi': 2},
   'components': {'co': 126.9,
    'no': 0,
    'no2': 3.68,
    'o3': 64.12,
    'so2': 2.06,
    'pm2_5': 10.58,
    'pm10': 34.11,
    'nh3': 10.09},
   'dt': 1780498800},
  {'main': {'aqi': 2},
   'components': {'co': 122.32,
    'no': 0,
    'no2': 3.61,
    'o3': 55.85,
    'so2': 2.26,
    'pm2_5': 10.52,
    'pm10': 37.49,
    'nh3': 9.99},
   'dt': 1780502400},
  {'main': {'aqi': 2},
   'components': {'co': 120.43,
    'no': 0,
    'no2': 3.68,
    'o3': 49.2,
    'so2': 2.42,
    'pm2_5': 10.98,
    'pm10': 41.85,
    'nh3': 10.31},
   'dt': 1780506000},
  {'main': {'aqi': 2},
   'components': {'co': 117.74,
    'no': 0,
    'no2': 3.73,
    'o3': 44.07,
    'so2': 2.48,
    'pm2_5': 11.51,
    'pm10': 45.9,
    'nh3': 10.71},
   'dt': 1780509600},
  {'main': {'aqi': 2},
   'components': {'co': 111.53,
    'no': 0,
    'no2': 3.49,
    'o3': 39.42,
    'so2': 2.4,
    'pm2_5': 11.83,
    'pm10': 49.21,
    'nh3': 10.69},
   'dt': 1780513200},
  {'main': {'aqi': 3},
   'components': {'co': 106.63,
    'no': 0,
    'no2': 3.18,
    'o3': 36.24,
    'so2': 2.22,
    'pm2_5': 12.13,
    'pm10': 51.78,
    'nh3': 10.68},
   'dt': 1780516800},
  {'main': {'aqi': 3},
   'components': {'co': 102.9,
    'no': 0,
    'no2': 2.86,
    'o3': 34.77,
    'so2': 2.02,
    'pm2_5': 12.31,
    'pm10': 52.96,
    'nh3': 10.41},
   'dt': 1780520400},
  {'main': {'aqi': 3},
   'components': {'co': 99.77,
    'no': 0,
    'no2': 2.59,
    'o3': 34.42,
    'so2': 1.84,
    'pm2_5': 12.34,
    'pm10': 52.92,
    'nh3': 10},
   'dt': 1780524000},
  {'main': {'aqi': 3},
   'components': {'co': 97.87,
    'no': 0,
    'no2': 2.4,
    'o3': 34.77,
    'so2': 1.7,
    'pm2_5': 12.38,
    'pm10': 52.68,
    'nh3': 9.79},
   'dt': 1780527600},
  {'main': {'aqi': 3},
   'components': {'co': 97.09,
    'no': 0,
    'no2': 2.33,
    'o3': 35.11,
    'so2': 1.6,
    'pm2_5': 12.44,
    'pm10': 52.53,
    'nh3': 9.58},
   'dt': 1780531200},
  {'main': {'aqi': 3},
   'components': {'co': 98.04,
    'no': 0,
    'no2': 2.47,
    'o3': 35,
    'so2': 1.57,
    'pm2_5': 12.45,
    'pm10': 52.31,
    'nh3': 9.53},
   'dt': 1780534800},
  {'main': {'aqi': 3},
   'components': {'co': 101.68,
    'no': 0.14,
    'no2': 2.78,
    'o3': 35.17,
    'so2': 1.68,
    'pm2_5': 12.49,
    'pm10': 52.27,
    'nh3': 9.58},
   'dt': 1780538400},
  {'main': {'aqi': 3},
   'components': {'co': 104.06,
    'no': 0.5,
    'no2': 2.57,
    'o3': 37.46,
    'so2': 1.84,
    'pm2_5': 12.5,
    'pm10': 52.12,
    'nh3': 8.94},
   'dt': 1780542000},
  {'main': {'aqi': 2},
   'components': {'co': 101.16,
    'no': 0.46,
    'no2': 1.87,
    'o3': 46.52,
    'so2': 1.78,
    'pm2_5': 11.95,
    'pm10': 48.36,
    'nh3': 7.08},
   'dt': 1780545600},
  {'main': {'aqi': 2},
   'components': {'co': 99.55,
    'no': 0.29,
    'no2': 1.3,
    'o3': 59.09,
    'so2': 1.65,
    'pm2_5': 11.52,
    'pm10': 43.15,
    'nh3': 6.2},
   'dt': 1780549200},
  {'main': {'aqi': 2},
   'components': {'co': 99.55,
    'no': 0.2,
    'no2': 0.99,
    'o3': 68.52,
    'so2': 1.63,
    'pm2_5': 11.75,
    'pm10': 40.11,
    'nh3': 5.7},
   'dt': 1780552800},
  {'main': {'aqi': 2},
   'components': {'co': 101.45,
    'no': 0.15,
    'no2': 0.83,
    'o3': 76.03,
    'so2': 1.57,
    'pm2_5': 11.89,
    'pm10': 37.68,
    'nh3': 5.15},
   'dt': 1780556400},
  {'main': {'aqi': 2},
   'components': {'co': 102.82,
    'no': 0.13,
    'no2': 0.76,
    'o3': 79.57,
    'so2': 1.45,
    'pm2_5': 12.02,
    'pm10': 36.7,
    'nh3': 4.89},
   'dt': 1780560000},
  {'main': {'aqi': 2},
   'components': {'co': 102.59,
    'no': 0.13,
    'no2': 0.76,
    'o3': 79.39,
    'so2': 1.37,
    'pm2_5': 11.98,
    'pm10': 36.56,
    'nh3': 4.65},
   'dt': 1780563600},
  {'main': {'aqi': 2},
   'components': {'co': 103.39,
    'no': 0.13,
    'no2': 0.87,
    'o3': 78.69,
    'so2': 1.33,
    'pm2_5': 11.91,
    'pm10': 36.8,
    'nh3': 4.71},
   'dt': 1780567200},
  {'main': {'aqi': 2},
   'components': {'co': 103.97,
    'no': 0.16,
    'no2': 1.17,
    'o3': 75.3,
    'so2': 1.31,
    'pm2_5': 11.51,
    'pm10': 36.42,
    'nh3': 5.13},
   'dt': 1780570800},
  {'main': {'aqi': 2},
   'components': {'co': 104.88,
    'no': 0.18,
    'no2': 1.69,
    'o3': 70.39,
    'so2': 1.32,
    'pm2_5': 10.96,
    'pm10': 36.01,
    'nh3': 5.58},
   'dt': 1780574400},
  {'main': {'aqi': 2},
   'components': {'co': 106.05,
    'no': 0.13,
    'no2': 2.24,
    'o3': 64.84,
    'so2': 1.37,
    'pm2_5': 10.57,
    'pm10': 36.56,
    'nh3': 6.06},
   'dt': 1780578000},
  {'main': {'aqi': 2},
   'components': {'co': 106.54,
    'no': 0.02,
    'no2': 2.6,
    'o3': 59.15,
    'so2': 1.5,
    'pm2_5': 10.47,
    'pm10': 37.92,
    'nh3': 6.42},
   'dt': 1780581600},
  {'main': {'aqi': 2},
   'components': {'co': 106.74,
    'no': 0,
    'no2': 2.62,
    'o3': 54.7,
    'so2': 1.61,
    'pm2_5': 10.67,
    'pm10': 39.44,
    'nh3': 6.69},
   'dt': 1780585200},
  {'main': {'aqi': 2},
   'components': {'co': 104.88,
    'no': 0,
    'no2': 2.51,
    'o3': 50.54,
    'so2': 1.64,
    'pm2_5': 10.89,
    'pm10': 40.21,
    'nh3': 6.75},
   'dt': 1780588800},
  {'main': {'aqi': 2},
   'components': {'co': 104.63,
    'no': 0,
    'no2': 2.48,
    'o3': 48.14,
    'so2': 1.67,
    'pm2_5': 11.36,
    'pm10': 41.84,
    'nh3': 6.94},
   'dt': 1780592400},
  {'main': {'aqi': 2},
   'components': {'co': 102.83,
    'no': 0,
    'no2': 2.44,
    'o3': 46.18,
    'so2': 1.66,
    'pm2_5': 11.77,
    'pm10': 43.48,
    'nh3': 7.09},
   'dt': 1780596000},
  {'main': {'aqi': 2},
   'components': {'co': 98.27,
    'no': 0,
    'no2': 2.28,
    'o3': 43.97,
    'so2': 1.59,
    'pm2_5': 11.95,
    'pm10': 44.71,
    'nh3': 7.15},
   'dt': 1780599600},
  {'main': {'aqi': 2},
   'components': {'co': 94.91,
    'no': 0,
    'no2': 2.09,
    'o3': 42.36,
    'so2': 1.53,
    'pm2_5': 12.19,
    'pm10': 46.39,
    'nh3': 7.34},
   'dt': 1780603200},
  {'main': {'aqi': 2},
   'components': {'co': 91.9,
    'no': 0,
    'no2': 1.92,
    'o3': 41.29,
    'so2': 1.46,
    'pm2_5': 12.44,
    'pm10': 48.07,
    'nh3': 7.51},
   'dt': 1780606800},
  {'main': {'aqi': 2},
   'components': {'co': 89.43,
    'no': 0,
    'no2': 1.79,
    'o3': 40.64,
    'so2': 1.4,
    'pm2_5': 12.62,
    'pm10': 49.3,
    'nh3': 7.67},
   'dt': 1780610400},
  {'main': {'aqi': 3},
   'components': {'co': 88.31,
    'no': 0,
    'no2': 1.74,
    'o3': 40.67,
    'so2': 1.35,
    'pm2_5': 12.81,
    'pm10': 50.18,
    'nh3': 7.99},
   'dt': 1780614000},
  {'main': {'aqi': 3},
   'components': {'co': 88.53,
    'no': 0,
    'no2': 1.78,
    'o3': 41.13,
    'so2': 1.32,
    'pm2_5': 12.94,
    'pm10': 50.41,
    'nh3': 8.25},
   'dt': 1780617600},
  {'main': {'aqi': 2},
   'components': {'co': 90.41,
    'no': 0,
    'no2': 2,
    'o3': 41.55,
    'so2': 1.34,
    'pm2_5': 12.89,
    'pm10': 49.54,
    'nh3': 8.43},
   'dt': 1780621200},
  {'main': {'aqi': 2},
   'components': {'co': 94.68,
    'no': 0.09,
    'no2': 2.39,
    'o3': 42.43,
    'so2': 1.45,
    'pm2_5': 12.65,
    'pm10': 47.43,
    'nh3': 8.29},
   'dt': 1780624800},
  {'main': {'aqi': 2},
   'components': {'co': 96.91,
    'no': 0.31,
    'no2': 2.33,
    'o3': 45.23,
    'so2': 1.58,
    'pm2_5': 12.08,
    'pm10': 43.94,
    'nh3': 7.36},
   'dt': 1780628400},
  {'main': {'aqi': 2},
   'components': {'co': 94.54,
    'no': 0.28,
    'no2': 1.72,
    'o3': 51.67,
    'so2': 1.53,
    'pm2_5': 10.78,
    'pm10': 38.35,
    'nh3': 5.61},
   'dt': 1780632000},
  {'main': {'aqi': 2},
   'components': {'co': 93.46,
    'no': 0.2,
    'no2': 1.3,
    'o3': 58.05,
    'so2': 1.44,
    'pm2_5': 9.77,
    'pm10': 34.22,
    'nh3': 4.83},
   'dt': 1780635600},
  {'main': {'aqi': 2},
   'components': {'co': 92.92,
    'no': 0.16,
    'no2': 1.12,
    'o3': 62.39,
    'so2': 1.46,
    'pm2_5': 9.71,
    'pm10': 33.35,
    'nh3': 4.66},
   'dt': 1780639200},
  {'main': {'aqi': 2},
   'components': {'co': 94.33,
    'no': 0.14,
    'no2': 1.02,
    'o3': 67.21,
    'so2': 1.46,
    'pm2_5': 10.14,
    'pm10': 33.82,
    'nh3': 4.5},
   'dt': 1780642800},
  {'main': {'aqi': 2},
   'components': {'co': 94.92,
    'no': 0.14,
    'no2': 0.94,
    'o3': 71.35,
    'so2': 1.37,
    'pm2_5': 10.65,
    'pm10': 34.38,
    'nh3': 4.32},
   'dt': 1780646400},
  {'main': {'aqi': 2},
   'components': {'co': 95.43,
    'no': 0.15,
    'no2': 0.92,
    'o3': 73.85,
    'so2': 1.34,
    'pm2_5': 11.4,
    'pm10': 36.18,
    'nh3': 4.36},
   'dt': 1780650000},
  {'main': {'aqi': 2},
   'components': {'co': 97.7,
    'no': 0.16,
    'no2': 1,
    'o3': 76.57,
    'so2': 1.33,
    'pm2_5': 12.3,
    'pm10': 38.53,
    'nh3': 4.68},
   'dt': 1780653600},
  {'main': {'aqi': 2},
   'components': {'co': 99.89,
    'no': 0.17,
    'no2': 1.24,
    'o3': 76.78,
    'so2': 1.32,
    'pm2_5': 12.64,
    'pm10': 39.53,
    'nh3': 5.1},
   'dt': 1780657200},
  {'main': {'aqi': 2},
   'components': {'co': 102.06,
    'no': 0.18,
    'no2': 1.67,
    'o3': 74.44,
    'so2': 1.34,
    'pm2_5': 12.55,
    'pm10': 39.67,
    'nh3': 5.38},
   'dt': 1780660800},
  {'main': {'aqi': 2},
   'components': {'co': 103.39,
    'no': 0.12,
    'no2': 2.17,
    'o3': 69.73,
    'so2': 1.43,
    'pm2_5': 12.41,
    'pm10': 40.38,
    'nh3': 5.63},
   'dt': 1780664400},
  {'main': {'aqi': 2},
   'components': {'co': 104.86,
    'no': 0.02,
    'no2': 2.62,
    'o3': 64.6,
    'so2': 1.61,
    'pm2_5': 12.74,
    'pm10': 43.07,
    'nh3': 6.08},
   'dt': 1780668000},
  {'main': {'aqi': 2},
   'components': {'co': 105.74,
    'no': 0,
    'no2': 2.79,
    'o3': 60.49,
    'so2': 1.84,
    'pm2_5': 13.45,
    'pm10': 47.16,
    'nh3': 6.59},
   'dt': 1780671600},
  {'main': {'aqi': 3},
   'components': {'co': 104.28,
    'no': 0,
    'no2': 2.87,
    'o3': 55.24,
    'so2': 2.03,
    'pm2_5': 13.9,
    'pm10': 50.27,
    'nh3': 7.1},
   'dt': 1780675200},
  {'main': {'aqi': 3},
   'components': {'co': 105.68,
    'no': 0,
    'no2': 3.05,
    'o3': 51.17,
    'so2': 2.19,
    'pm2_5': 14.46,
    'pm10': 53.33,
    'nh3': 8.05},
   'dt': 1780678800},
  {'main': {'aqi': 3},
   'components': {'co': 106.28,
    'no': 0,
    'no2': 3.18,
    'o3': 48.06,
    'so2': 2.27,
    'pm2_5': 15.01,
    'pm10': 56.17,
    'nh3': 9.04},
   'dt': 1780682400},
  {'main': {'aqi': 3},
   'components': {'co': 104.1,
    'no': 0,
    'no2': 3.06,
    'o3': 45.25,
    'so2': 2.22,
    'pm2_5': 15.46,
    'pm10': 58.88,
    'nh3': 9.76},
   'dt': 1780686000},
  {'main': {'aqi': 3},
   'components': {'co': 101.53,
    'no': 0,
    'no2': 2.78,
    'o3': 42.87,
    'so2': 2.04,
    'pm2_5': 15.83,
    'pm10': 60.98,
    'nh3': 10.3},
   'dt': 1780689600},
  {'main': {'aqi': 3},
   'components': {'co': 99.18,
    'no': 0,
    'no2': 2.53,
    'o3': 41.44,
    'so2': 1.83,
    'pm2_5': 16.16,
    'pm10': 62.57,
    'nh3': 10.59},
   'dt': 1780693200},
  {'main': {'aqi': 3},
   'components': {'co': 96.96,
    'no': 0,
    'no2': 2.3,
    'o3': 40.75,
    'so2': 1.63,
    'pm2_5': 16.52,
    'pm10': 63.94,
    'nh3': 10.58},
   'dt': 1780696800},
  {'main': {'aqi': 3},
   'components': {'co': 95.76,
    'no': 0,
    'no2': 2.15,
    'o3': 40.84,
    'so2': 1.48,
    'pm2_5': 17.05,
    'pm10': 66.03,
    'nh3': 10.53},
   'dt': 1780700400},
  {'main': {'aqi': 3},
   'components': {'co': 95.15,
    'no': 0,
    'no2': 2.09,
    'o3': 41.2,
    'so2': 1.38,
    'pm2_5': 17.63,
    'pm10': 68.37,
    'nh3': 10.29},
   'dt': 1780704000},
  {'main': {'aqi': 3},
   'components': {'co': 95.31,
    'no': 0,
    'no2': 2.18,
    'o3': 41.09,
    'so2': 1.36,
    'pm2_5': 18.06,
    'pm10': 70.49,
    'nh3': 10.08},
   'dt': 1780707600},
  {'main': {'aqi': 3},
   'components': {'co': 97.51,
    'no': 0.1,
    'no2': 2.4,
    'o3': 41.39,
    'so2': 1.45,
    'pm2_5': 18.56,
    'pm10': 73.35,
    'nh3': 10},
   'dt': 1780711200},
  {'main': {'aqi': 3},
   'components': {'co': 98.33,
    'no': 0.36,
    'no2': 2.19,
    'o3': 43.87,
    'so2': 1.61,
    'pm2_5': 19.03,
    'pm10': 76.24,
    'nh3': 9.26},
   'dt': 1780714800},
  {'main': {'aqi': 3},
   'components': {'co': 94.62,
    'no': 0.31,
    'no2': 1.51,
    'o3': 52.51,
    'so2': 1.57,
    'pm2_5': 18.42,
    'pm10': 73.8,
    'nh3': 6.97},
   'dt': 1780718400},
  {'main': {'aqi': 3},
   'components': {'co': 92.97,
    'no': 0.21,
    'no2': 1.03,
    'o3': 62.54,
    'so2': 1.43,
    'pm2_5': 17.12,
    'pm10': 66.54,
    'nh3': 5.87},
   'dt': 1780722000},
  {'main': {'aqi': 3},
   'components': {'co': 92.7,
    'no': 0.15,
    'no2': 0.8,
    'o3': 69.99,
    'so2': 1.34,
    'pm2_5': 16.18,
    'pm10': 60.1,
    'nh3': 5.34},
   'dt': 1780725600},
  {'main': {'aqi': 3},
   'components': {'co': 93.76,
    'no': 0.12,
    'no2': 0.69,
    'o3': 76.07,
    'so2': 1.26,
    'pm2_5': 15.15,
    'pm10': 53.95,
    'nh3': 4.76},
   'dt': 1780729200},
  {'main': {'aqi': 2},
   'components': {'co': 93.98,
    'no': 0.11,
    'no2': 0.63,
    'o3': 79,
    'so2': 1.15,
    'pm2_5': 14.15,
    'pm10': 48.92,
    'nh3': 4.4},
   'dt': 1780732800},
  {'main': {'aqi': 2},
   'components': {'co': 94.09,
    'no': 0.1,
    'no2': 0.62,
    'o3': 79.93,
    'so2': 1.08,
    'pm2_5': 13.58,
    'pm10': 46.21,
    'nh3': 4.22},
   'dt': 1780736400},
  {'main': {'aqi': 2},
   'components': {'co': 95.73,
    'no': 0.1,
    'no2': 0.66,
    'o3': 81.7,
    'so2': 1.06,
    'pm2_5': 13.74,
    'pm10': 46.4,
    'nh3': 4.27},
   'dt': 1780740000},
  {'main': {'aqi': 2},
   'components': {'co': 97.09,
    'no': 0.11,
    'no2': 0.79,
    'o3': 82.22,
    'so2': 1.07,
    'pm2_5': 14.1,
    'pm10': 47.8,
    'nh3': 4.46},
   'dt': 1780743600},
  {'main': {'aqi': 2},
   'components': {'co': 98.17,
    'no': 0.12,
    'no2': 1.02,
    'o3': 80.87,
    'so2': 1.11,
    'pm2_5': 14.4,
    'pm10': 49.62,
    'nh3': 4.68},
   'dt': 1780747200},
  {'main': {'aqi': 3},
   'components': {'co': 100.73,
    'no': 0.08,
    'no2': 1.49,
    'o3': 76.98,
    'so2': 1.19,
    'pm2_5': 14.85,
    'pm10': 52.32,
    'nh3': 5.36},
   'dt': 1780750800},
  {'main': {'aqi': 3},
   'components': {'co': 104.21,
    'no': 0.01,
    'no2': 2.09,
    'o3': 70.31,
    'so2': 1.35,
    'pm2_5': 15.64,
    'pm10': 56.36,
    'nh3': 6.57},
   'dt': 1780754400},
  {'main': {'aqi': 3},
   'components': {'co': 106.76,
    'no': 0,
    'no2': 2.43,
    'o3': 64.19,
    'so2': 1.56,
    'pm2_5': 16.75,
    'pm10': 61.32,
    'nh3': 7.66},
   'dt': 1780758000},
  {'main': {'aqi': 3},
   'components': {'co': 105.46,
    'no': 0,
    'no2': 2.53,
    'o3': 57.77,
    'so2': 1.71,
    'pm2_5': 17.43,
    'pm10': 64.34,
    'nh3': 8.27},
   'dt': 1780761600},
  {'main': {'aqi': 3},
   'components': {'co': 105.1,
    'no': 0,
    'no2': 2.59,
    'o3': 53.71,
    'so2': 1.82,
    'pm2_5': 18.05,
    'pm10': 67.11,
    'nh3': 8.84},
   'dt': 1780765200},
  {'main': {'aqi': 3},
   'components': {'co': 103.52,
    'no': 0,
    'no2': 2.57,
    'o3': 50.27,
    'so2': 1.82,
    'pm2_5': 18.28,
    'pm10': 68.42,
    'nh3': 9.34},
   'dt': 1780768800},
  {'main': {'aqi': 3},
   'components': {'co': 99.2,
    'no': 0,
    'no2': 2.4,
    'o3': 46.33,
    'so2': 1.71,
    'pm2_5': 17.92,
    'pm10': 67.62,
    'nh3': 9.58},
   'dt': 1780772400},
  {'main': {'aqi': 3},
   'components': {'co': 96.23,
    'no': 0,
    'no2': 2.21,
    'o3': 43.19,
    'so2': 1.58,
    'pm2_5': 17.52,
    'pm10': 66.33,
    'nh3': 9.92},
   'dt': 1780776000},
  {'main': {'aqi': 3},
   'components': {'co': 94.11,
    'no': 0,
    'no2': 2.07,
    'o3': 40.96,
    'so2': 1.45,
    'pm2_5': 17.19,
    'pm10': 64.97,
    'nh3': 10.2},
   'dt': 1780779600},
  {'main': {'aqi': 3},
   'components': {'co': 92.42,
    'no': 0,
    'no2': 1.99,
    'o3': 39.21,
    'so2': 1.31,
    'pm2_5': 16.91,
    'pm10': 63.68,
    'nh3': 10.59},
   'dt': 1780783200},
  {'main': {'aqi': 3},
   'components': {'co': 92.42,
    'no': 0,
    'no2': 1.99,
    'o3': 38.06,
    'so2': 1.2,
    'pm2_5': 16.9,
    'pm10': 63.25,
    'nh3': 11.34},
   'dt': 1780786800},
  {'main': {'aqi': 3},
   'components': {'co': 93.52,
    'no': 0,
    'no2': 2.09,
    'o3': 37.31,
    'so2': 1.12,
    'pm2_5': 17.03,
    'pm10': 63.69,
    'nh3': 12.05},
   'dt': 1780790400},
  {'main': {'aqi': 3},
   'components': {'co': 96.03,
    'no': 0,
    'no2': 2.34,
    'o3': 36.52,
    'so2': 1.12,
    'pm2_5': 17.2,
    'pm10': 64.78,
    'nh3': 12.64},
   'dt': 1780794000},
  {'main': {'aqi': 3},
   'components': {'co': 100.74,
    'no': 0.12,
    'no2': 2.69,
    'o3': 36.38,
    'so2': 1.24,
    'pm2_5': 17.49,
    'pm10': 66.85,
    'nh3': 12.81},
   'dt': 1780797600},
  {'main': {'aqi': 3},
   'components': {'co': 102.95,
    'no': 0.44,
    'no2': 2.5,
    'o3': 38.94,
    'so2': 1.45,
    'pm2_5': 17.84,
    'pm10': 69.68,
    'nh3': 12.03},
   'dt': 1780801200},
  {'main': {'aqi': 3},
   'components': {'co': 96.46,
    'no': 0.36,
    'no2': 1.68,
    'o3': 48.74,
    'so2': 1.59,
    'pm2_5': 17.54,
    'pm10': 70.03,
    'nh3': 8.61},
   'dt': 1780804800},
  {'main': {'aqi': 3},
   'components': {'co': 94.42,
    'no': 0.24,
    'no2': 1.17,
    'o3': 59.33,
    'so2': 1.52,
    'pm2_5': 17.06,
    'pm10': 66.87,
    'nh3': 7.22},
   'dt': 1780808400}]}

In [63]:
d={'aqi':[],'co':[],'no':[],'no2':[],'o3':[],'so2':[],'pm2_5':[],'pm10':[],'nh3':[]}
for i in result['list']:
    d['aqi'].append(i['main']['aqi'])
    d['co'].append(i['components']['co'])
    d['no'].append(i['components']['no'])
    d['no2'].append(i['components']['no2'])
    d['o3'].append(i['components']['o3'])
    d['so2'].append(i['components']['so2'])
    d['pm2_5'].append(i['components']['pm2_5'])
    d['pm10'].append(i['components']['pm10'])
    d['nh3'].append(i['components']['nh3'])
df= pd.DataFrame(d)
df

    aqi      co    no   no2     o3   so2  pm2_5   pm10    nh3
0     2  110.29  0.29  1.45  62.74  2.13  14.02  42.60   9.30
1     2  108.92  0.19  1.04  72.43  1.80  14.49  40.34   8.21
2     2  106.57  0.14  0.85  76.33  1.43  13.31  35.19   7.05
3     2  106.47  0.13  0.84  78.54  1.30  12.80  33.05   6.74
4     2  110.24  0.14  1.01  81.24  1.27  12.69  32.31   7.21
..  ...     ...   ...   ...    ...   ...    ...    ...    ...
91    3   96.03  0.00  2.34  36.52  1.12  17.20  64.78  12.64
92    3  100.74  0.12  2.69  36.38  1.24  17.49  66.85  12.81
93    3  102.95  0.44  2.50  38.94  1.45  17.84  69.68  12.03
94    3   96.46  0.36  1.68  48.74  1.59  17.54  70.03   8.61
95    3   94.42  0.24  1.17  59.33  1.52  17.06  66.87   7.22

[96 rows x 9 columns]

In [68]:
url4=f'https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API_key}'
response= requests.get(url4)
response.status_code
result=response.json()
result

{'coord': {'lon': 72.5801, 'lat': 23.0215},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01d'}],
 'base': 'stations',
 'main': {'temp': 312.25,
  'feels_like': 315.82,
  'temp_min': 312.25,
  'temp_max': 312.25,
  'pressure': 1004,
  'humidity': 33,
  'sea_level': 1004,
  'grnd_level': 999},
 'visibility': 10000,
 'wind': {'speed': 1.59, 'deg': 249, 'gust': 1.43},
 'clouds': {'all': 0},
 'dt': 1780470865,
 'sys': {'country': 'IN', 'sunrise': 1780446232, 'sunset': 1780494720},
 'timezone': 19800,
 'id': 1279233,
 'name': 'Ahmedabad',
 'cod': 200}

In [75]:
print('temp min',result['main']['temp_min'])
print('temp max',result['main']['temp_max'])
print(result['main']['pressure'])
print(result['weather'][0]['description'])
print(result['wind']['speed'] )
print(result['clouds']['all'] )
print(result['visibility'])

temp min 312.25
temp max 312.25
1004
clear sky
1.59
0
10000

In [91]:
url5=f'http://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API_key}'
response = requests.get(url5)
result=response.json()
result

d={'dt_txt':[],'temp':[],'temp_min':[],'temp_max':[],'pressure':[],'description':[],'humidity':[],'wind_speed':[],'clouad_all':[],'visibility':[]}
    
for i in result['list']:
    
     d['description'].append(i['weather'][0]['description'])
     d['dt_txt'].append(i['dt_txt'])
     d['temp'].append(i['main']['temp'])
     d['temp_min'].append(i['main']['temp_min'])
     d['temp_max'].append(i['main']['temp_max'])
     d['pressure'].append(i['main']['pressure'])
     d['humidity'].append(i['main']['humidity'])
     d['wind_speed'].append(i['wind']['speed'])
     d['clouad_all'].append(i['clouds']['all'])
     d['visibility'].append(i['visibility'])

d
df2= pd.DataFrame(d)
df2

,dt_txt,temp,temp_min,temp_max,pressure,description,humidity,wind_speed,clouad_all,visibility
0,2026-06-03 09:00:00,313.42,313.42,313.42,1002,few clouds,28,1.66,15,10000
1,2026-06-03 12:00:00,313.14,312.59,313.14,1001,light rain,29,7.12,21,10000
2,2026-06-03 15:00:00,302.73,297.38,302.73,1004,heavy intensity rain,62,8.81,42,1955
3,2026-06-03 18:00:00,301.28,301.28,301.28,1005,heavy intensity rain,58,5.30,77,10000
4,2026-06-03 21:00:00,302.50,302.50,302.50,1002,overcast clouds,50,2.94,100,10000
5,2026-06-04 00:00:00,302.05,302.05,302.05,1005,broken clouds,58,1.99,84,10000
6,2026-06-04 03:00:00,304.77,304.77,304.77,1005,scattered clouds,56,3.83,48,10000
7,2026-06-04 06:00:00,309.45,309.45,309.45,1004,scattered clouds,39,5.32,42,10000
8,2026-06-04 09:00:00,312.61,312.61,312.61,1002,few clouds,31,5.45,24,10000
9,2026-06-04 12:00:00,312.16,312.16,312.16,1000,few clouds,33,6.98,12,10000
10,2026-06-04 15:00:00,306.17,306.17,306.17,1002,clear sky,54,6.65,0,10000
11,2026-06-04 18:00:00,307.23,307.23,307.23,1003,scattered clouds,48,4.54,33,10000
12,2026-06-04 21:00:00,304.97,304.97,304.97,1003,light rain,53,5.20,31,10000
13,2026-06-05 00:00:00,303.44,303.44,303.44,1004,few clouds,60,5.26,15,10000
14,2026-06-05 03:00:00,305.24,305.24,305.24,1005,clear sky,53,5.68,0,10000
15,2026-06-05 06:00:00,309.48,309.48,309.48,1005,clear sky,38,5.46,0,10000
16,2026-06-05 09:00:00,312.83,312.83,312.83,1002,clear sky,29,5.51,0,10000
17,2026-06-05 12:00:00,312.35,312.35,312.35,1000,clear sky,32,6.98,0,10000
18,2026-06-05 15:00:00,306.42,306.42,306.42,1002,clear sky,55,6.40,1,10000
19,2026-06-05 18:00:00,307.14,307.14,307.14,1004,clear sky,49,4.28,2,10000
20,2026-06-05 21:00:00,305.13,305.13,305.13,1004,clear sky,52,5.22,0,10000
21,2026-06-06 00:00:00,304.09,304.09,304.09,1005,clear sky,55,4.48,0,10000
22,2026-06-06 03:00:00,305.36,305.36,305.36,1007,clear sky,51,5.33,0,10000
23,2026-06-06 06:00:00,309.77,309.77,309.77,1006,clear sky,36,5.81,0,10000
24,2026-06-06 09:00:00,313.39,313.39,313.39,1003,clear sky,25,5.65,0,10000
25,2026-06-06 12:00:00,313.39,313.39,313.39,1001,clear sky,26,6.73,0,10000
26,2026-06-06 15:00:00,306.68,306.68,306.68,1004,clear sky,52,6.68,0,10000
27,2026-06-06 18:00:00,306.79,306.79,306.79,1006,clear sky,48,1.89,0,10000
28,2026-06-06 21:00:00,305.42,305.42,305.42,1005,clear sky,50,5.47,0,10000
29,2026-06-07 00:00:00,304.27,304.27,304.27,1006,clear sky,54,4.56,0,10000
30,2026-06-07 03:00:00,305.39,305.39,305.39,1008,clear sky,50,5.45,0,10000
31,2026-06-07 06:00:00,309.81,309.81,309.81,1006,clear sky,35,5.61,0,10000
32,2026-06-07 09:00:00,314.06,314.06,314.06,1003,clear sky,23,5.81,0,10000
33,2026-06-07 12:00:00,313.49,313.49,313.49,1002,clear sky,27,7.72,0,10000
34,2026-06-07 15:00:00,306.68,306.68,306.68,1004,clear sky,53,4.92,0,10000
35,2026-06-07 18:00:00,305.81,305.81,305.81,1006,clear sky,53,5.77,0,10000
36,2026-06-07 21:00:00,304.78,304.78,304.78,1005,clear sky,52,5.59,0,10000
37,2026-06-08 00:00:00,303.14,303.14,303.14,1005,clear sky,60,4.74,0,10000
38,2026-06-08 03:00:00,304.70,304.70,304.70,1006,clear sky,54,5.50,0,10000
39,2026-06-08 06:00:00,309.79,309.79,309.79,1005,clear sky,35,7.01,0,10000

In [86]:
print(json.dumps(result,indent=5))

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1780477200,
               "main": {
                    "temp": 314.68,
                    "feels_like": 316.89,
                    "temp_min": 314.68,
                    "temp_max": 314.68,
                    "pressure": 1001,
                    "sea_level": 1001,
                    "grnd_level": 996,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02d"
                    }
               ],
               "clouds": {
                    "all": 15
               },
               "wind": {
                    "speed": 1.66,
                    "deg": 124,
                    "gust": 2.58
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-06-03 09:00:00"
          },
          {
               "dt": 1780488000,
               "main": {
                    "temp": 313.98,
                    "feels_like": 316.52,
                    "temp_min": 312.59,
                    "temp_max": 313.98,
                    "pressure": 1001,
                    "sea_level": 1001,
                    "grnd_level": 994,
                    "humidity": 27,
                    "temp_kf": 1.39
               },
               "weather": [
                    {
                         "id": 500,
                         "main": "Rain",
                         "description": "light rain",
                         "icon": "10d"
                    }
               ],
               "clouds": {
                    "all": 21
               },
               "wind": {
                    "speed": 7.12,
                    "deg": 200,
                    "gust": 6.3
               },
               "visibility": 10000,
               "pop": 0.61,
               "rain": {
                    "3h": 0.76
               },
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-06-03 12:00:00"
          },
          {
               "dt": 1780498800,
               "main": {
                    "temp": 303.15,
                    "feels_like": 306.18,
                    "temp_min": 297.38,
                    "temp_max": 303.15,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 1000,
                    "humidity": 61,
                    "temp_kf": 5.77
               },
               "weather": [
                    {
                         "id": 502,
                         "main": "Rain",
                         "description": "heavy intensity rain",
                         "icon": "10n"
                    }
               ],
               "clouds": {
                    "all": 42
               },
               "wind": {
                    "speed": 8.81,
                    "deg": 50,
                    "gust": 18.42
               },
               "visibility": 1955,
               "pop": 1,
               "rain": {
                    "3h": 22.05
               },
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-06-03 15:00:00"
          },
          {
               "dt": 1780509600,
               "main": {
                    "temp": 301.28,
                    "feels_like": 302.57,
                    "temp_min": 301.28,
                    "temp_max": 301.28,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 999,
                    "humidity": 58,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 502,
                         "main": "Rain",
                         "description": "heavy intensity rain",
                         "icon": "10n"
                    }
               ],
               "clouds": {
                    "all": 77
               },
               "wind": {
                    "speed": 5.3,
                    "deg": 258,
                    "gust": 8.55
               },
               "visibility": 10000,
               "pop": 1,
               "rain": {
                    "3h": 13.19
               },
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-06-03 18:00:00"
          },
          {
               "dt": 1780520400,
               "main": {
                    "temp": 302.5,
                    "feels_like": 303.28,
                    "temp_min": 302.5,
                    "temp_max": 302.5,
                    "pressure": 1002,
                    "sea_level": 1002,
                    "grnd_level": 997,
                    "humidity": 50,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 804,
                         "main": "Clouds",
                         "description": "overcast clouds",
                         "icon": "04n"
                    }
               ],
               "clouds": {
                    "all": 100
               },
               "wind": {
                    "speed": 2.94,
                    "deg": 231,
                    "gust": 5.18
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-06-03 21:00:00"
          },
          {
               "dt": 1780531200,
               "main": {
                    "temp": 302.05,
                    "feels_like": 303.72,
                    "temp_min": 302.05,
                    "temp_max": 302.05,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 999,
                    "humidity": 58,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 803,
                         "main": "Clouds",
                         "description": "broken clouds",
                         "icon": "04n"
                    }
               ],
               "clouds": {
                    "all": 84
               },
               "wind": {
                    "speed": 1.99,
                    "deg": 135,
                    "gust": 2.03
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-06-04 00:00:00"
          },
          {
               "dt": 1780542000,
               "main": {
                    "temp": 304.77,
                    "feels_like": 308.27,
                    "temp_min": 304.77,
                    "temp_max": 304.77,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 56,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 48
               },
               "wind": {
                    "speed": 3.83,
                    "deg": 206,
                    "gust": 4.99
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-06-04 03:00:00"
          },
          {
               "dt": 1780552800,
               "main": {
                    "temp": 309.45,
                    "feels_like": 312.54,
                    "temp_min": 309.45,
                    "temp_max": 309.45,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 999,
                    "humidity": 39,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 42
               },
               "wind": {
                    "speed": 5.32,
                    "deg": 216,
                    "gust": 5.75
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-06-04 06:00:00"
          },
          {
               "dt": 1780563600,
               "main": {
                    "temp": 312.61,
                    "feels_like": 315.67,
                    "temp_min": 312.61,
                    "temp_max": 312.61,
                    "pressure": 1002,
                    "sea_level": 1002,
                    "grnd_level": 996,
                    "humidity": 31,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02d"
                    }
               ],
               "clouds": {
                    "all": 24
               },
               "wind": {
                    "speed": 5.45,
                    "deg": 229,
                    "gust": 5.92
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-06-04 09:00:00"
          },
          {
               "dt": 1780574400,
               "main": {
                    "temp": 312.16,
                    "feels_like": 315.63,
                    "temp_min": 312.16,
                    "temp_max": 312.16,
                    "pressure": 1000,
                    "sea_level": 1000,
                    "grnd_level": 995,
                    "humidity": 33,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02d"
                    }
               ],
               "clouds": {
                    "all": 12
               },
               "wind": {
                    "speed": 6.98,
                    "deg": 190,
                    "gust": 7.08
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-06-04 12:00:00"
          },
          {
               "dt": 1780585200,
               "main": {
                    "temp": 306.17,
                    "feels_like": 310.69,
                    "temp_min": 306.17,
                    "temp_max": 306.17,
                    "pressure": 1002,
                    "sea_level": 1002,
                    "grnd_level": 997,
                    "humidity": 54,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.65,
                    "deg": 166,
                    "gust": 10.65
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-06-04 15:00:00"
          },
          {
               "dt": 1780596000,
               "main": {
                    "temp": 307.23,
                    "feels_like": 311.05,
                    "temp_min": 307.23,
                    "temp_max": 307.23,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 998,
                    "humidity": 48,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03n"
                    }
               ],
               "clouds": {
                    "all": 33
               },
               "wind": {
                    "speed": 4.54,
                    "deg": 255,
                    "gust": 6.67
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-06-04 18:00:00"
          },
          {
               "dt": 1780606800,
               "main": {
                    "temp": 304.97,
                    "feels_like": 307.91,
                    "temp_min": 304.97,
                    "temp_max": 304.97,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 998,
                    "humidity": 53,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 500,
                         "main": "Rain",
                         "description": "light rain",
                         "icon": "10n"
                    }
               ],
               "clouds": {
                    "all": 31
               },
               "wind": {
                    "speed": 5.2,
                    "deg": 223,
                    "gust": 7
               },
               "visibility": 10000,
               "pop": 0.32,
               "rain": {
                    "3h": 0.23
               },
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-06-04 21:00:00"
          },
          {
               "dt": 1780617600,
               "main": {
                    "temp": 303.44,
                    "feels_like": 306.54,
                    "temp_min": 303.44,
                    "temp_max": 303.44,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 998,
                    "humidity": 60,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02n"
                    }
               ],
               "clouds": {
                    "all": 15
               },
               "wind": {
                    "speed": 5.26,
                    "deg": 217,
                    "gust": 7.48
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-06-05 00:00:00"
          },
          {
               "dt": 1780628400,
               "main": {
                    "temp": 305.24,
                    "feels_like": 308.44,
                    "temp_min": 305.24,
                    "temp_max": 305.24,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 53,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.68,
                    "deg": 220,
                    "gust": 7.05
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-06-05 03:00:00"
          },
          {
               "dt": 1780639200,
               "main": {
                    "temp": 309.48,
                    "feels_like": 312.25,
                    "temp_min": 309.48,
                    "temp_max": 309.48,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 38,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.46,
                    "deg": 225,
                    "gust": 6.37
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-06-05 06:00:00"
          },
          {
               "dt": 1780650000,
               "main": {
                    "temp": 312.83,
                    "feels_like": 315.25,
                    "temp_min": 312.83,
                    "temp_max": 312.83,
                    "pressure": 1002,
                    "sea_level": 1002,
                    "grnd_level": 997,
                    "humidity": 29,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.51,
                    "deg": 239,
                    "gust": 6.19
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-06-05 09:00:00"
          },
          {
               "dt": 1780660800,
               "main": {
                    "temp": 312.35,
                    "feels_like": 315.59,
                    "temp_min": 312.35,
                    "temp_max": 312.35,
                    "pressure": 1000,
                    "sea_level": 1000,
                    "grnd_level": 995,
                    "humidity": 32,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {