In [1]:
import numpy as np 
import pandas as pd

In [2]:
df=pd.read_csv('social_media_engagement.csv')
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [3]:
df.isna().sum()

post_id            0
platform           0
post_type          0
post_time          0
likes              0
comments           0
shares             0
post_day           0
sentiment_score    0
dtype: int64

In [4]:
df['sentiment_score']

0     positive
1      neutral
2     negative
3     negative
4     positive
        ...
95    positive
96     neutral
97    positive
98    positive
99     neutral
Name: sentiment_score, Length: 100, dtype: object

In [13]:
df.groupby('platform')[['likes','comments','shares']].sum()

            likes  comments  shares
platform
Facebook    86392      7965   15180
Instagram  107994      8368   18906
Twitter     43795      3933    7479

In [ ]:
df=