In [12]:
import pandas as pd  
import numpy as np

se=pd.Series(['A','B',"C"])
se

0    A
1    B
2    C
dtype: object

In [14]:
df=pd.DataFrame([[1,2,3],
                                    [4,5,6],
                                    [7,8,9]],columns=se,index=se)
df

   A  B  C
A  1  2  3
B  4  5  6
C  7  8  9

In [16]:
df.head(2)

   A  B  C
A  1  2  3
B  4  5  6

In [17]:
df.tail(2)

   A  B  C
B  4  5  6
C  7  8  9

In [29]:
df.sample(1)

   A  B  C
B  4  5  6

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [33]:
df

   A  B  C
A  1  2  3
B  4  5  6
C  7  8  9

In [32]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

      name region    sales  expances
0  William   None  50000.0   42000.0
1     Emma  North  52000.0   43000.0
2    Sofia   East      NaN       NaN
3   Markus   None      NaN       NaN
4     YAYA  North  56000.0   65220.0

   name region    sales  expances
1  Emma  North  52000.0   43000.0
4  YAYA  North  56000.0   65220.0

   name region    sales  expances
1  Emma  North  52000.0   43000.0
4  YAYA  North  56000.0   65220.0